/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.solifsd08.slay.stencil;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author solil
 */
public class MegaGUI extends javax.swing.JFrame {

    /**
     * Creates new form MegaGUI
     */
    public MegaGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroupFractalType = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        radioHLines = new javax.swing.JRadioButton();
        radioTOutlines = new javax.swing.JRadioButton();
        radioTShapes = new javax.swing.JRadioButton();
        titleFractalFactory = new javax.swing.JLabel();
        labelFractalType = new javax.swing.JLabel();
        labelIndicateMaxLevels = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        buttonMakeFractal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        colorsList = new javax.swing.JList<>();
        labelFractalType1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fractal Factory By Soli :)");
        setResizable(false);

        radioGroupFractalType.add(radioHLines);
        radioHLines.setText("Horizontal Lines");
        radioHLines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioHLinesActionPerformed(evt);
            }
        });

        radioGroupFractalType.add(radioTOutlines);
        radioTOutlines.setText("Triangles (Outlines)");
        radioTOutlines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTOutlinesActionPerformed(evt);
            }
        });

        radioGroupFractalType.add(radioTShapes);
        radioTShapes.setText("Triangles (Shapes)");
        radioTShapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTShapesActionPerformed(evt);
            }
        });

        titleFractalFactory.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        titleFractalFactory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleFractalFactory.setText("Fractal Factory");
        titleFractalFactory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelFractalType.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        labelFractalType.setText("Fractal Type:");

        labelIndicateMaxLevels.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        labelIndicateMaxLevels.setText("Maximum Depth:");

        jSpinner1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(11, 2, 33, 1));
        jSpinner1.setAutoscrolls(true);
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner1, ""));
        jSpinner1.setInheritsPopupMenu(true);
        jSpinner1.setName(""); // NOI18N

        jLabel1.setText("(max levels to calculate)");

        buttonMakeFractal.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        buttonMakeFractal.setText("Make My Fractal!");
        buttonMakeFractal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMakeFractalActionPerformed(evt);
            }
        });

        colorsList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.yellow, java.awt.Color.red, java.awt.Color.magenta, java.awt.Color.blue));
        colorsList.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        colorsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Red", "Green", "Blue", "Surprise Me!" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        colorsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(colorsList);

        labelFractalType1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        labelFractalType1.setText("Favorite Color:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFractalType)
                                    .addComponent(radioHLines, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioTShapes)
                                    .addComponent(radioTOutlines))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSpinner1)
                                    .addComponent(labelIndicateMaxLevels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelFractalType1)
                                        .addGap(48, 48, 48))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1)
                                        .addGap(17, 17, 17))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonMakeFractal, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(titleFractalFactory, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleFractalFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFractalType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioHLines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioTOutlines)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioTShapes))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIndicateMaxLevels)
                            .addComponent(labelFractalType1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(buttonMakeFractal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioHLinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioHLinesActionPerformed
        selectedFractalType = 0;
    }//GEN-LAST:event_radioHLinesActionPerformed

    private void radioTShapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTShapesActionPerformed
        selectedFractalType = 2;
    }//GEN-LAST:event_radioTShapesActionPerformed

    private void radioTOutlinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTOutlinesActionPerformed
        selectedFractalType = 1;
    }//GEN-LAST:event_radioTOutlinesActionPerformed

    private void buttonMakeFractalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMakeFractalActionPerformed
        
        // get color
        Color faveColor;
        switch (colorsList.getSelectedIndex()) {
            case 0: faveColor = new Color(255, 0, 0);
            case 1: faveColor = new Color(255, 0, 0);
            case 2: faveColor = new Color(255, 0, 0);
            case 3: faveColor = randomColor();
            default: faveColor = randomColor();
        }
        
        // Generate fractal window!
        switch (selectedFractalType) {
            case 1: FractalFun.setupTheWindow();
            case 2: FractalFun.setupTheWindow();
            case 0: FractalFun.setupTheWindow();
            default: FractalFun.setupTheWindow();
        }
        
        // TODO: FEATURES:
        // pass fave color to FractalFun.setupTheWindow() -- fill background that color
        // pass fractalType to ^ -- chooses which fractal method to run
        // pass maxLevel to ^ -- indicates max level (add to the "stop recursion here" checks)
        
    }//GEN-LAST:event_buttonMakeFractalActionPerformed

    public static void runMegaGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MegaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MegaGUI().setVisible(true);
                
            }
        });
    }
    
    // fields
    int selectedFractalType = 0; //default is 0. 0=lines, 1=triLine, 2=triShape
    

    // get random color
    private Color randomColor() {
        Random random = new Random();
        int red = random.nextInt(256);
        int green = random.nextInt(256);
        int blue = random.nextInt(256);
        return new Color(red, green, blue);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMakeFractal;
    private javax.swing.JList<String> colorsList;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelFractalType;
    private javax.swing.JLabel labelFractalType1;
    private javax.swing.JLabel labelIndicateMaxLevels;
    private javax.swing.ButtonGroup radioGroupFractalType;
    private javax.swing.JRadioButton radioHLines;
    private javax.swing.JRadioButton radioTOutlines;
    private javax.swing.JRadioButton radioTShapes;
    private javax.swing.JLabel titleFractalFactory;
    // End of variables declaration//GEN-END:variables
}
